file_object = open('some_file.txt', 'a')
file_object.write('We are exploring the file append mode.')
file_object.close()

new_file = open('history.txt','w')
new_file.write('This is a file that contains history notes.')
new_file.write('\n')
new_file.write('Once there lived a king and his queen.')
new_file.write('\n')
new_file.write('And then they died!')
new_file.write('\n')
new_file.write('End of the story,Dear!')
new_file.close()

nf = open('history.txt','r')
nf_data = nf.read()
print()
print('Let\'s revise the history notes')
print()
print(nf_data)
print()
nf.close()


f = open('some_file.txt','r')
file_data = f.read()
print()
print('File Content:')
print('------------')
print()
print(file_data)
print('------------')
print()
f.close()
